#docker run --detach --rm --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest
services:
  restreamer:
    container_name: restreamer
    image: datarhei/restreamer:latest
    ports:
      - "8081:8080"
      - "8181:8181"
      - "1935:1935"
      - "1936:1936"
      - "6000:6000/udp"
    volumes:
      - /opt/core/config:/core/config
      - /opt/core/data:/core/data
    environment:
      - TZ=Europe/Berlin
    restart: always
    privileged: true

volumes:
  restreamer:
    driver: local
